language: node_js

sudo: required

node_js:
  - "node"

services:
  - docker

before_install:
  - cd .. && git clone --depth 1 https://github.com/cablelabs/lpwanserver.git

install: npm ci

before_script:
  - cd ../lpwanserver && ./bin/demo && cd ../lpwanserver-web-client

script:
  - ./bin/e2e

after_script:
  - cd ../lpwanserver && ./bin/demo stop && cd ../lpwanserver-web-client
