language: node_js

sudo: required

node_js:
  - "node"

services:
  - docker

install: npm ci

before_script:
  - ./bin/package.js
  - git clone https://github.com/cablelabs/lpwanserver.git
  - docker-compose -f ./lpwanserver/docker/docker-compose.loraserver.yml -f ./lpwanserver/docker/docker-compose.demo.yml up -d

script:
  - ./bin/e2e.js

after_script:
  - docker-compose -f ./lpwanserver/docker/docker-compose.loraserver.yml -f ./lpwanserver/docker/docker-compose.demo.yml down

deploy:
  provider: script
  script: ./bin/publish.js
  on:
    branch: master
