language: node_js

sudo: required

node_js:
  - "node"

services:
  - docker

install: npm ci

before_script:
  - ./bin/package.js

script:
  - ./bin/e2e.js

deploy:
  provider: script
  script: ./bin/publish.js
  on:
    branch: master
