language: node_js

sudo: required

node_js:
  - "node"

services:
  - docker

install: npm install

before_script:
  - ./bin/package.js

script:
  - ./bin/e2e.js

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script:
    - docker push lpwanserver/lpwanserver-web-client
    - docker push lpwanserver/browser-test
  on:
    branch: master
