language: node_js

sudo: required

node_js:
  - "node"

services:
  - docker

install: npm ci

before_script:
  - ./bin/package.js
  - cd .. && git clone --depth 1 https://github.com/cablelabs/lpwanserver.git && cd lpwanserver-web-client

script:
  - ./bin/e2e

deploy:
  provider: script
  script: ./bin/publish.js
  on:
    branch: master
