language: node_js

sudo: required

node_js:
  - "node"

services:
  - docker

script:
  - ./bin/e2e.js

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push lpwanserver/lpwanserver-web-client