language: node_js

sudo: required

node_js:
  - "node"

services:
  - docker

before_install:
  - cd .. && git clone --depth 1 https://github.com/cablelabs/lpwanserver.git
  - cd ../lpwanserver && npm install && ./bin/generate-development-certs && cd ../lpwanserver-web-client

install: npm ci

before_script:
  - ./bin/package.js

script:
  - ./bin/e2e
