FROM node:10.15-alpine

# set working directory
WORKDIR /usr/src/app

# Copy project file
COPY package*.json ./

# install ALL node_modules
RUN npm install

# copy all project
COPY . .

ENV BROWSER=
ENV HUB_HOST=
ENV HUB_PORT=
ENV WEB_CLIENT_HOST=
ENV WEB_CLIENT_PORT=
ENV TTN_CLIENT_ID=
ENV TTN_CLIENT_SECRET=
ENV TTN_USERNAME=
ENV TTN_PASSWORD=
ENV TTN_ENABLED=

CMD [ "npm", "run", "test:e2e" ]
