version: "3"
services:
  selenium_hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium_hub
    environment:
      - HUB_HOST=selenium_hub
      - HUB_PORT=4444
    ports:
      - 5900:5900

  # firefox:
  #   image: selenium/node-firefox-debug
  #   depends_on:
  #     - selenium_hub
  #   environment:
  #     - HUB_HOST=selenium_hub
  #     - HUB_PORT=4444
  #   ports:
  #    - 5901:5900

  # browser_test_chrome:
  #   image: lpwanserver/browser-test
  #   depends_on:
  #     - lpwanserver
  #     - chrome
  #   environment:
  #     - BROWSER=chrome
  #     - HUB_HOST=selenium_hub
  #     - HUB_PORT=4444
  #     - WEB_CLIENT_HOST=lpwanserver_web_client
  #     - WEB_CLIENT_PORT=80
  #     - LORA_SERVER_HOST=lora_appserver
  #     - LORA_SERVER_PORT=8080
  #     - LORA_SERVER_V1_HOST=lora_appserver1
  #     - LORA_SERVER_V1_PORT=8080

  # browser_test_firefox:
  #   image: lpwanserver/browser-test
  #   depends_on:
  #     - lpwanserver
  #     - firefox
  #   environment:
  #     - BROWSER=firefox
  #     - HUB_HOST=selenium_hub
  #     - HUB_PORT=4444
  #     - WEB_CLIENT_HOST=lpwanserver_web_client
  #     - WEB_CLIENT_PORT=80
  #     - LORA_SERVER_HOST=lora_appserver
  #     - LORA_SERVER_PORT=8080
  #     - LORA_SERVER_V1_HOST=lora_appserver1
  #     - LORA_SERVER_V1_PORT=8080

  lpwanserver:
    image: lpwanserver/lpwanserver
    depends_on:
      - loraserver
      - lora_appserver
    environment:
      - NODE_ENV=local
      - PORT=3200
      - db_file=data/demo_data/demo.sqlite3
    ports:
      - 3200:3200

  lpwanserver_web_client:
    image: lpwanserver/browser-test-ui-server
    ports:
      - 80:80

  loraserver:
    image: loraserver/loraserver:2
    depends_on:
      - postgresql
      - redis
      - mosquitto
    volumes:
      - ./configuration/loraserver:/etc/loraserver

  loraserver1:
    image: loraserver/loraserver:1
    depends_on:
    - postgresql
    - redis
    - mosquitto
    volumes:
    - ./configuration/loraserver_1:/etc/loraserver

  lora_appserver:
    image: loraserver/lora-app-server:2
    depends_on:
      - postgresql
      - redis
      - mosquitto
    ports:
      - 8080:8080
    volumes:
      - ./configuration/lora-app-server:/etc/lora-app-server

  lora_appserver1:
    image: loraserver/lora-app-server:1
    depends_on:
    - postgresql
    - redis
    - mosquitto
    ports:
    - 8081:8080
    volumes:
    - ./configuration/lora-app-server_1:/etc/lora-app-server
  
  postgresql:
    image: postgres:9.6-alpine
    ports:
      - 5432
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - ../e2e/data/postgresql:/var/lib/postgresql/data

  redis:
    image: redis:4-alpine
    ports:
      - 6379
    volumes:
      - ../e2e/data/redis:/data

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883